//
// Milkyway Hierarchical Verilog Dump:
// Generated on 12/20/2017 at 08:11:25
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :cruisecontrol
// Cell Name    :cruisecontrol
// Hierarchy delimiter:'/'
// Write Command : write_verilog ./output/cruisecontrol_icc.v -pg -no_physical_only_cells
//


module cruisecontrol_DW01_inc_1 (SUM , A , VDD , VSS );
output [7:0] SUM ;
input  [7:0] A ;
input  VDD ;
input  VSS ;

supply1 VDD ;
supply0 VSS ;

wire [7:2] carry ;

XOR2_X1 U2 (.A ( carry[7] ) , .B ( A[7] ) , .Z ( SUM[7] ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
INV_X1 U1 (.A ( A[0] ) , .ZN ( SUM[0] ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
HA_X1 U1_1_1 (.A ( A[1] ) , .B ( A[0] ) , .CO ( carry[2] ) , .S ( SUM[1] ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
HA_X1 U1_1_2 (.A ( A[2] ) , .B ( carry[2] ) , .CO ( carry[3] ) , .S ( SUM[2] ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
HA_X1 U1_1_3 (.A ( A[3] ) , .B ( carry[3] ) , .CO ( carry[4] ) , .S ( SUM[3] ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
HA_X1 U1_1_4 (.A ( A[4] ) , .B ( carry[4] ) , .CO ( carry[5] ) , .S ( SUM[4] ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
HA_X1 U1_1_5 (.A ( A[5] ) , .B ( carry[5] ) , .CO ( carry[6] ) , .S ( SUM[5] ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
HA_X1 U1_1_6 (.A ( A[6] ) , .B ( carry[6] ) , .CO ( carry[7] ) , .S ( SUM[6] ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
endmodule




module cruisecontrol_DW01_inc_0 (SUM , A , VDD , VSS );
output [7:0] SUM ;
input  [7:0] A ;
input  VDD ;
input  VSS ;

supply1 VDD ;
supply0 VSS ;

wire [7:2] carry ;

XOR2_X1 U2 (.A ( carry[7] ) , .B ( A[7] ) , .Z ( SUM[7] ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
INV_X1 U1 (.A ( A[0] ) , .ZN ( SUM[0] ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
HA_X1 U1_1_1 (.A ( A[1] ) , .B ( A[0] ) , .CO ( carry[2] ) , .S ( SUM[1] ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
HA_X1 U1_1_2 (.A ( A[2] ) , .B ( carry[2] ) , .CO ( carry[3] ) , .S ( SUM[2] ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
HA_X1 U1_1_3 (.A ( A[3] ) , .B ( carry[3] ) , .CO ( carry[4] ) , .S ( SUM[3] ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
HA_X1 U1_1_4 (.A ( A[4] ) , .B ( carry[4] ) , .CO ( carry[5] ) , .S ( SUM[4] ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
HA_X1 U1_1_5 (.A ( A[5] ) , .B ( carry[5] ) , .CO ( carry[6] ) , .S ( SUM[5] ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
HA_X1 U1_1_6 (.A ( A[6] ) , .B ( carry[6] ) , .CO ( carry[7] ) , .S ( SUM[6] ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
endmodule




module cruisecontrol (speed , cruisespeed , reset , clk , cruisectrl , 
    brake , resume , cancel , coast , accel , set , throttle );
output [7:0] speed ;
output [7:0] cruisespeed ;
input  reset ;
input  clk ;
output cruisectrl ;
input  brake ;
input  resume ;
input  cancel ;
input  coast ;
input  accel ;
input  set ;
input  throttle ;

supply1 VDD ;
supply0 VSS ;

wire SPARE_PREFIX_NAME_0_19_A1 ;
assign SPARE_PREFIX_NAME_0_19_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_19_A1_A2 ;
assign SPARE_PREFIX_NAME_0_19_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_18_A1 ;
assign SPARE_PREFIX_NAME_0_18_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_18_A1_A2 ;
assign SPARE_PREFIX_NAME_0_18_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_17_A1 ;
assign SPARE_PREFIX_NAME_0_17_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_17_A1_A2 ;
assign SPARE_PREFIX_NAME_0_17_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_16_A1 ;
assign SPARE_PREFIX_NAME_0_16_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_16_A1_A2 ;
assign SPARE_PREFIX_NAME_0_16_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_15_A1 ;
assign SPARE_PREFIX_NAME_0_15_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_15_A1_A2 ;
assign SPARE_PREFIX_NAME_0_15_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_14_A1 ;
assign SPARE_PREFIX_NAME_0_14_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_14_A1_A2 ;
assign SPARE_PREFIX_NAME_0_14_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_13_A1 ;
assign SPARE_PREFIX_NAME_0_13_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_13_A1_A2 ;
assign SPARE_PREFIX_NAME_0_13_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_12_A1 ;
assign SPARE_PREFIX_NAME_0_12_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_12_A1_A2 ;
assign SPARE_PREFIX_NAME_0_12_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_11_A1 ;
assign SPARE_PREFIX_NAME_0_11_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_11_A1_A2 ;
assign SPARE_PREFIX_NAME_0_11_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_10_A1 ;
assign SPARE_PREFIX_NAME_0_10_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_10_A1_A2 ;
assign SPARE_PREFIX_NAME_0_10_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_9_A1 ;
assign SPARE_PREFIX_NAME_0_9_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_9_A1_A2 ;
assign SPARE_PREFIX_NAME_0_9_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_8_A1 ;
assign SPARE_PREFIX_NAME_0_8_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_8_A1_A2 ;
assign SPARE_PREFIX_NAME_0_8_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_7_A1 ;
assign SPARE_PREFIX_NAME_0_7_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_7_A1_A2 ;
assign SPARE_PREFIX_NAME_0_7_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_6_A1 ;
assign SPARE_PREFIX_NAME_0_6_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_6_A1_A2 ;
assign SPARE_PREFIX_NAME_0_6_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_5_A1 ;
assign SPARE_PREFIX_NAME_0_5_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_5_A1_A2 ;
assign SPARE_PREFIX_NAME_0_5_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_4_A1 ;
assign SPARE_PREFIX_NAME_0_4_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_4_A1_A2 ;
assign SPARE_PREFIX_NAME_0_4_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_3_A1 ;
assign SPARE_PREFIX_NAME_0_3_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_3_A1_A2 ;
assign SPARE_PREFIX_NAME_0_3_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_2_A1 ;
assign SPARE_PREFIX_NAME_0_2_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_2_A1_A2 ;
assign SPARE_PREFIX_NAME_0_2_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_1_A1 ;
assign SPARE_PREFIX_NAME_0_1_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_1_A1_A2 ;
assign SPARE_PREFIX_NAME_0_1_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_0_A1 ;
assign SPARE_PREFIX_NAME_0_0_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_0_A1_A2 ;
assign SPARE_PREFIX_NAME_0_0_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_19_A1 ;
assign SPARE_PREFIX_NAME_19_A1 = 1'b0;
wire SPARE_PREFIX_NAME_19_A1_A2 ;
assign SPARE_PREFIX_NAME_19_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_18_A1 ;
assign SPARE_PREFIX_NAME_18_A1 = 1'b0;
wire SPARE_PREFIX_NAME_18_A1_A2 ;
assign SPARE_PREFIX_NAME_18_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_17_A1 ;
assign SPARE_PREFIX_NAME_17_A1 = 1'b0;
wire SPARE_PREFIX_NAME_17_A1_A2 ;
assign SPARE_PREFIX_NAME_17_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_16_A1 ;
assign SPARE_PREFIX_NAME_16_A1 = 1'b0;
wire SPARE_PREFIX_NAME_16_A1_A2 ;
assign SPARE_PREFIX_NAME_16_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_15_A1 ;
assign SPARE_PREFIX_NAME_15_A1 = 1'b0;
wire SPARE_PREFIX_NAME_15_A1_A2 ;
assign SPARE_PREFIX_NAME_15_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_14_A1 ;
assign SPARE_PREFIX_NAME_14_A1 = 1'b0;
wire SPARE_PREFIX_NAME_14_A1_A2 ;
assign SPARE_PREFIX_NAME_14_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_13_A1 ;
assign SPARE_PREFIX_NAME_13_A1 = 1'b0;
wire SPARE_PREFIX_NAME_13_A1_A2 ;
assign SPARE_PREFIX_NAME_13_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_12_A1 ;
assign SPARE_PREFIX_NAME_12_A1 = 1'b0;
wire SPARE_PREFIX_NAME_12_A1_A2 ;
assign SPARE_PREFIX_NAME_12_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_11_A1 ;
assign SPARE_PREFIX_NAME_11_A1 = 1'b0;
wire SPARE_PREFIX_NAME_11_A1_A2 ;
assign SPARE_PREFIX_NAME_11_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_10_A1 ;
assign SPARE_PREFIX_NAME_10_A1 = 1'b0;
wire SPARE_PREFIX_NAME_10_A1_A2 ;
assign SPARE_PREFIX_NAME_10_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_9_A1 ;
assign SPARE_PREFIX_NAME_9_A1 = 1'b0;
wire SPARE_PREFIX_NAME_9_A1_A2 ;
assign SPARE_PREFIX_NAME_9_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_8_A1 ;
assign SPARE_PREFIX_NAME_8_A1 = 1'b0;
wire SPARE_PREFIX_NAME_8_A1_A2 ;
assign SPARE_PREFIX_NAME_8_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_7_A1 ;
assign SPARE_PREFIX_NAME_7_A1 = 1'b0;
wire SPARE_PREFIX_NAME_7_A1_A2 ;
assign SPARE_PREFIX_NAME_7_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_6_A1 ;
assign SPARE_PREFIX_NAME_6_A1 = 1'b0;
wire SPARE_PREFIX_NAME_6_A1_A2 ;
assign SPARE_PREFIX_NAME_6_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_5_A1 ;
assign SPARE_PREFIX_NAME_5_A1 = 1'b0;
wire SPARE_PREFIX_NAME_5_A1_A2 ;
assign SPARE_PREFIX_NAME_5_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_4_A1 ;
assign SPARE_PREFIX_NAME_4_A1 = 1'b0;
wire SPARE_PREFIX_NAME_4_A1_A2 ;
assign SPARE_PREFIX_NAME_4_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_3_A1 ;
assign SPARE_PREFIX_NAME_3_A1 = 1'b0;
wire SPARE_PREFIX_NAME_3_A1_A2 ;
assign SPARE_PREFIX_NAME_3_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_2_A1 ;
assign SPARE_PREFIX_NAME_2_A1 = 1'b0;
wire SPARE_PREFIX_NAME_2_A1_A2 ;
assign SPARE_PREFIX_NAME_2_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_1_A1 ;
assign SPARE_PREFIX_NAME_1_A1 = 1'b0;
wire SPARE_PREFIX_NAME_1_A1_A2 ;
assign SPARE_PREFIX_NAME_1_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_A1 ;
assign SPARE_PREFIX_NAME_0_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_A1_A2 ;
assign SPARE_PREFIX_NAME_0_A1_A2 = 1'b0;
wire [7:3] r116_carry ;
wire [2:0] state ;


cruisecontrol_DW01_inc_1 r113 (
    .SUM ( {n2 , n3 , n4 , n5 , n6 , n7 , n8 , n9 } ) , .A ( speed ) , 
    .VDD ( VDD ) , .VSS ( VSS ) ) ;


cruisecontrol_DW01_inc_0 add_118 (
    .SUM ( {N153 , N152 , N151 , N150 , N149 , N148 , N147 , N146 } ) , 
    .A ( cruisespeed ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;

BUF_X1 U114 (.A ( n285 ) , .Z ( n338 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_19 (.A1 ( SPARE_PREFIX_NAME_0_19_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_19_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_18 (.A1 ( SPARE_PREFIX_NAME_0_18_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_18_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_17 (.A1 ( SPARE_PREFIX_NAME_0_17_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_17_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_16 (.A1 ( SPARE_PREFIX_NAME_0_16_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_16_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_15 (.A1 ( SPARE_PREFIX_NAME_0_15_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_15_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_14 (.A1 ( SPARE_PREFIX_NAME_0_14_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_14_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_13 (.A1 ( SPARE_PREFIX_NAME_0_13_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_13_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_12 (.A1 ( SPARE_PREFIX_NAME_0_12_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_12_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_11 (.A1 ( SPARE_PREFIX_NAME_0_11_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_11_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_10 (.A1 ( SPARE_PREFIX_NAME_0_10_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_10_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_9 (.A1 ( SPARE_PREFIX_NAME_0_9_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_9_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_8 (.A1 ( SPARE_PREFIX_NAME_0_8_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_8_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_7 (.A1 ( SPARE_PREFIX_NAME_0_7_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_7_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_6 (.A1 ( SPARE_PREFIX_NAME_0_6_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_6_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_5 (.A1 ( SPARE_PREFIX_NAME_0_5_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_5_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_4 (.A1 ( SPARE_PREFIX_NAME_0_4_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_4_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_3 (.A1 ( SPARE_PREFIX_NAME_0_3_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_3_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_2 (.A1 ( SPARE_PREFIX_NAME_0_2_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_2_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_1 (.A1 ( SPARE_PREFIX_NAME_0_1_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_1_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_0 (.A1 ( SPARE_PREFIX_NAME_0_0_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_0_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X4 SPARE_PREFIX_NAME_19 (.A1 ( SPARE_PREFIX_NAME_19_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_19_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X4 SPARE_PREFIX_NAME_18 (.A1 ( SPARE_PREFIX_NAME_18_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_18_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X4 SPARE_PREFIX_NAME_17 (.A1 ( SPARE_PREFIX_NAME_17_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_17_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X4 SPARE_PREFIX_NAME_16 (.A1 ( SPARE_PREFIX_NAME_16_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_16_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X4 SPARE_PREFIX_NAME_15 (.A1 ( SPARE_PREFIX_NAME_15_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_15_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X4 SPARE_PREFIX_NAME_14 (.A1 ( SPARE_PREFIX_NAME_14_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_14_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X4 SPARE_PREFIX_NAME_13 (.A1 ( SPARE_PREFIX_NAME_13_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_13_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X4 SPARE_PREFIX_NAME_12 (.A1 ( SPARE_PREFIX_NAME_12_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_12_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X4 SPARE_PREFIX_NAME_11 (.A1 ( SPARE_PREFIX_NAME_11_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_11_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X4 SPARE_PREFIX_NAME_10 (.A1 ( SPARE_PREFIX_NAME_10_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_10_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X4 SPARE_PREFIX_NAME_9 (.A1 ( SPARE_PREFIX_NAME_9_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_9_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X4 SPARE_PREFIX_NAME_8 (.A1 ( SPARE_PREFIX_NAME_8_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_8_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X4 SPARE_PREFIX_NAME_7 (.A1 ( SPARE_PREFIX_NAME_7_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_7_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X4 SPARE_PREFIX_NAME_6 (.A1 ( SPARE_PREFIX_NAME_6_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_6_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X4 SPARE_PREFIX_NAME_5 (.A1 ( SPARE_PREFIX_NAME_5_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_5_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X4 SPARE_PREFIX_NAME_4 (.A1 ( SPARE_PREFIX_NAME_4_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_4_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X4 SPARE_PREFIX_NAME_3 (.A1 ( SPARE_PREFIX_NAME_3_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_3_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X4 SPARE_PREFIX_NAME_2 (.A1 ( SPARE_PREFIX_NAME_2_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_2_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X4 SPARE_PREFIX_NAME_1 (.A1 ( SPARE_PREFIX_NAME_1_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_1_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X4 SPARE_PREFIX_NAME_0 (.A1 ( SPARE_PREFIX_NAME_0_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_A1_A2 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U252 (.A ( n187 ) , .ZN ( n221 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U253 (.A ( n180 ) , .ZN ( n220 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OR2_X1 U254 (.A1 ( speed[2] ) , .A2 ( speed[1] ) , .ZN ( r116_carry[3] ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OR2_X1 U255 (.A1 ( speed[3] ) , .A2 ( r116_carry[3] ) , .ZN ( r116_carry[4] ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OR2_X1 U256 (.A1 ( speed[4] ) , .A2 ( r116_carry[4] ) , .ZN ( r116_carry[5] ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OR2_X1 U257 (.A1 ( speed[5] ) , .A2 ( r116_carry[5] ) , .ZN ( r116_carry[6] ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OR2_X1 U258 (.A1 ( speed[6] ) , .A2 ( r116_carry[6] ) , .ZN ( r116_carry[7] ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR3_X1 U259 (.A1 ( state[1] ) , .A2 ( state[2] ) , .A3 ( n39 ) , .ZN ( n64 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND3_X1 U260 (.A1 ( n39 ) , .A2 ( n38 ) , .A3 ( state[2] ) , .ZN ( n720 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI21_X1 U261 (.A ( n720 ) , .B1 ( n118 ) , .B2 ( n730 ) , .ZN ( n83 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X1 U262 (.A1 ( n119 ) , .A2 ( n120 ) , .ZN ( n118 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
NAND4_X1 U263 (.A1 ( n213 ) , .A2 ( n155 ) , .A3 ( n311 ) , .A4 ( n298 ) 
    , .ZN ( n119 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND4_X1 U264 (.A1 ( N70 ) , .A2 ( n210 ) , .A3 ( n211 ) , .A4 ( n327 ) 
    , .ZN ( n120 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND3_X1 U265 (.A1 ( n39 ) , .A2 ( n33 ) , .A3 ( state[1] ) , .ZN ( n700 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND3_X1 U266 (.A1 ( state[0] ) , .A2 ( n38 ) , .A3 ( state[2] ) , .ZN ( n730 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND3_X1 U267 (.A1 ( n38 ) , .A2 ( n33 ) , .A3 ( n39 ) , .ZN ( n106 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X1 U268 (.A1 ( speed[1] ) , .A2 ( speed[0] ) , .ZN ( n1480 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
OAI21_X1 U269 (.A ( n156 ) , .B1 ( N70 ) , .B2 ( n210 ) , .ZN ( N71 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X1 U270 (.A1 ( n156 ) , .A2 ( speed[2] ) , .ZN ( n1490 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
OAI21_X1 U271 (.A ( n157 ) , .B1 ( n1480 ) , .B2 ( n211 ) , .ZN ( N72 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X1 U272 (.A1 ( n157 ) , .A2 ( speed[3] ) , .ZN ( n1500 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
OAI21_X1 U273 (.A ( n158 ) , .B1 ( n1490 ) , .B2 ( n327 ) , .ZN ( N73 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X1 U274 (.A1 ( n158 ) , .A2 ( speed[4] ) , .ZN ( n1510 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
OAI21_X1 U275 (.A ( n159 ) , .B1 ( n1500 ) , .B2 ( n213 ) , .ZN ( N74 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X1 U276 (.A1 ( n159 ) , .A2 ( speed[5] ) , .ZN ( n1520 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
OAI21_X1 U277 (.A ( n160 ) , .B1 ( n1510 ) , .B2 ( n155 ) , .ZN ( N75 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
XOR2_X1 U278 (.A ( speed[6] ) , .B ( n1520 ) , .Z ( N76 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
NOR2_X1 U279 (.A1 ( speed[6] ) , .A2 ( n160 ) , .ZN ( n1530 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
XOR2_X1 U280 (.A ( speed[7] ) , .B ( n1530 ) , .Z ( N77 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
NOR2_X1 U281 (.A1 ( cruisespeed[1] ) , .A2 ( cruisespeed[0] ) , .ZN ( n161 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI21_X1 U282 (.A ( n1700 ) , .B1 ( n218 ) , .B2 ( n1680 ) , .ZN ( N164 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X1 U283 (.A1 ( n1700 ) , .A2 ( cruisespeed[2] ) , .ZN ( n162 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI21_X1 U284 (.A ( n171 ) , .B1 ( n161 ) , .B2 ( n1690 ) , .ZN ( N165 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X1 U285 (.A1 ( n171 ) , .A2 ( cruisespeed[3] ) , .ZN ( n163 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI21_X1 U286 (.A ( n172 ) , .B1 ( n162 ) , .B2 ( n209 ) , .ZN ( N166 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X1 U287 (.A1 ( n172 ) , .A2 ( cruisespeed[4] ) , .ZN ( n1640 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI21_X1 U288 (.A ( n173 ) , .B1 ( n163 ) , .B2 ( n1670 ) , .ZN ( N167 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X1 U289 (.A1 ( n173 ) , .A2 ( cruisespeed[5] ) , .ZN ( n1650 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI21_X1 U290 (.A ( n174 ) , .B1 ( n1640 ) , .B2 ( n208 ) , .ZN ( N168 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
XOR2_X1 U291 (.A ( cruisespeed[6] ) , .B ( n1650 ) , .Z ( N169 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
NOR2_X1 U292 (.A1 ( cruisespeed[6] ) , .A2 ( n174 ) , .ZN ( n1660 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
XOR2_X1 U293 (.A ( cruisespeed[7] ) , .B ( n1660 ) , .Z ( N170 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
NOR2_X1 U294 (.A1 ( speed[7] ) , .A2 ( speed[6] ) , .ZN ( n177 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
AND3_X1 U295 (.A1 ( speed[3] ) , .A2 ( speed[2] ) , .A3 ( speed[1] ) 
    , .ZN ( n175 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI21_X1 U296 (.A ( speed[5] ) , .B1 ( n175 ) , .B2 ( speed[4] ) , .ZN ( n176 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X1 U297 (.A1 ( n177 ) , .A2 ( n176 ) , .ZN ( N58 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
NAND2_X1 U298 (.A1 ( cruisespeed[7] ) , .A2 ( n298 ) , .ZN ( n205 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X1 U299 (.A1 ( n213 ) , .A2 ( cruisespeed[4] ) , .ZN ( n182 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AND2_X1 U300 (.A1 ( speed[5] ) , .A2 ( n208 ) , .ZN ( n201 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
NOR2_X1 U301 (.A1 ( n182 ) , .A2 ( n201 ) , .ZN ( n185 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
OR2_X1 U302 (.A1 ( n211 ) , .A2 ( cruisespeed[2] ) , .ZN ( n181 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
NAND2_X1 U303 (.A1 ( cruisespeed[2] ) , .A2 ( n211 ) , .ZN ( n191 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X1 U304 (.A1 ( n181 ) , .A2 ( n191 ) , .ZN ( n192 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
NAND2_X1 U305 (.A1 ( speed[0] ) , .A2 ( n218 ) , .ZN ( n179 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
OR2_X1 U306 (.A1 ( n210 ) , .A2 ( n179 ) , .ZN ( n178 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
AOI22_X1 U307 (.A1 ( n210 ) , .A2 ( n179 ) , .B1 ( n178 ) 
    , .B2 ( cruisespeed[1] ) , .ZN ( n180 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X1 U308 (.A1 ( speed[3] ) , .A2 ( n209 ) , .ZN ( n194 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
OAI211_X1 U309 (.A ( n194 ) , .B ( n181 ) , .C1 ( n192 ) , .C2 ( n220 ) 
    , .ZN ( n183 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X1 U310 (.A1 ( n209 ) , .A2 ( speed[3] ) , .ZN ( n195 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
AND2_X1 U311 (.A1 ( cruisespeed[4] ) , .A2 ( n213 ) , .ZN ( n198 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X1 U312 (.A1 ( n182 ) , .A2 ( n198 ) , .ZN ( n199 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
NAND3_X1 U313 (.A1 ( n183 ) , .A2 ( n212 ) , .A3 ( n199 ) , .ZN ( n184 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X1 U314 (.A1 ( n208 ) , .A2 ( speed[5] ) , .ZN ( n200 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
AOI21_X1 U315 (.A ( n200 ) , .B1 ( n185 ) , .B2 ( n184 ) , .ZN ( n186 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
XNOR2_X1 U316 (.A ( speed[6] ) , .B ( cruisespeed[6] ) , .ZN ( n203 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI22_X1 U317 (.A1 ( speed[6] ) , .A2 ( n217 ) , .B1 ( n186 ) , .B2 ( n203 ) 
    , .ZN ( n187 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X1 U318 (.A1 ( n298 ) , .A2 ( cruisespeed[7] ) , .ZN ( n207 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI21_X1 U319 (.A ( n207 ) , .B1 ( n205 ) , .B2 ( n221 ) , .ZN ( n188 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X1 U320 (.A1 ( n218 ) , .A2 ( speed[0] ) , .ZN ( n1890 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
AND2_X1 U321 (.A1 ( n1890 ) , .A2 ( n210 ) , .ZN ( n1900 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
OAI22_X1 U322 (.A1 ( n1900 ) , .A2 ( cruisespeed[1] ) , .B1 ( n210 ) 
    , .B2 ( n1890 ) , .ZN ( n193 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI21_X1 U323 (.A ( n191 ) , .B1 ( n193 ) , .B2 ( n192 ) , .ZN ( n196 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI21_X1 U324 (.A ( n194 ) , .B1 ( n196 ) , .B2 ( n195 ) , .ZN ( n197 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI21_X1 U325 (.A ( n198 ) , .B1 ( n219 ) , .B2 ( n199 ) , .ZN ( n202 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI21_X1 U326 (.A ( n201 ) , .B1 ( n202 ) , .B2 ( n214 ) , .ZN ( n204 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI22_X1 U327 (.A1 ( cruisespeed[6] ) , .A2 ( n311 ) , .B1 ( n204 ) 
    , .B2 ( n203 ) , .ZN ( n206 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI21_X1 U328 (.A ( n205 ) , .B1 ( n207 ) , .B2 ( n206 ) , .ZN ( N190 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U159 (.A ( n1650 ) , .ZN ( n174 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U160 (.A ( n1480 ) , .ZN ( n156 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U161 (.A ( n161 ) , .ZN ( n1700 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U162 (.A ( n1510 ) , .ZN ( n159 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U163 (.A ( n1500 ) , .ZN ( n158 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U164 (.A ( n1490 ) , .ZN ( n157 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U165 (.A ( n1640 ) , .ZN ( n173 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U166 (.A ( n162 ) , .ZN ( n171 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U167 (.A ( n163 ) , .ZN ( n172 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U168 (.A ( n200 ) , .ZN ( n214 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U169 (.A ( n197 ) , .ZN ( n219 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U170 (.A ( n64 ) , .ZN ( n236 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X1 U171 (.A1 ( n720 ) , .A2 ( n730 ) , .ZN ( n65 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
NOR2_X1 U172 (.A1 ( cancel ) , .A2 ( brake ) , .ZN ( n127 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
NOR2_X1 U173 (.A1 ( n232 ) , .A2 ( accel ) , .ZN ( n114 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
INV_X1 U174 (.A ( n127 ) , .ZN ( n232 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI22_X1 U175 (.A1 ( n210 ) , .A2 ( n222 ) , .B1 ( n96 ) , .B2 ( n88 ) 
    , .ZN ( n143 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI222_X1 U176 (.VDD ( VDD ) , .VSS ( VSS ) , .A1 ( n8 ) , .A2 ( n89 ) 
    , .B1 ( n210 ) , .B2 ( n90 ) , .C1 ( N71 ) , .C2 ( n91 ) , .ZN ( n96 ) ) ;
OAI22_X1 U177 (.A1 ( n211 ) , .A2 ( n222 ) , .B1 ( n95 ) , .B2 ( n88 ) 
    , .ZN ( n142 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI222_X1 U178 (.VDD ( VDD ) , .VSS ( VSS ) , .A1 ( n7 ) , .A2 ( n89 ) 
    , .B1 ( N130 ) , .B2 ( n90 ) , .C1 ( N72 ) , .C2 ( n91 ) , .ZN ( n95 ) ) ;
XNOR2_X1 U179 (.A ( speed[2] ) , .B ( speed[1] ) , .ZN ( N130 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
OAI22_X1 U180 (.A1 ( n327 ) , .A2 ( n222 ) , .B1 ( n94 ) , .B2 ( n88 ) 
    , .ZN ( n141 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI222_X1 U181 (.VDD ( VDD ) , .VSS ( VSS ) , .A1 ( n6 ) , .A2 ( n89 ) 
    , .B1 ( N131 ) , .B2 ( n90 ) , .C1 ( N73 ) , .C2 ( n91 ) , .ZN ( n94 ) ) ;
XNOR2_X1 U182 (.A ( speed[3] ) , .B ( r116_carry[3] ) , .ZN ( N131 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI22_X1 U183 (.A1 ( n213 ) , .A2 ( n222 ) , .B1 ( n93 ) , .B2 ( n88 ) 
    , .ZN ( n140 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI222_X1 U184 (.VDD ( VDD ) , .VSS ( VSS ) , .A1 ( n5 ) , .A2 ( n89 ) 
    , .B1 ( N132 ) , .B2 ( n90 ) , .C1 ( N74 ) , .C2 ( n91 ) , .ZN ( n93 ) ) ;
XNOR2_X1 U185 (.A ( speed[4] ) , .B ( r116_carry[4] ) , .ZN ( N132 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI22_X1 U186 (.A1 ( n155 ) , .A2 ( n222 ) , .B1 ( n92 ) , .B2 ( n88 ) 
    , .ZN ( n139 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI222_X1 U187 (.VDD ( VDD ) , .VSS ( VSS ) , .A1 ( n4 ) , .A2 ( n89 ) 
    , .B1 ( N133 ) , .B2 ( n90 ) , .C1 ( N75 ) , .C2 ( n91 ) , .ZN ( n92 ) ) ;
XNOR2_X1 U188 (.A ( speed[5] ) , .B ( r116_carry[5] ) , .ZN ( N133 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI22_X1 U189 (.A1 ( n311 ) , .A2 ( n222 ) , .B1 ( n87 ) , .B2 ( n88 ) 
    , .ZN ( n138 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI222_X1 U190 (.VDD ( VDD ) , .VSS ( VSS ) , .A1 ( n3 ) , .A2 ( n89 ) 
    , .B1 ( N134 ) , .B2 ( n90 ) , .C1 ( N76 ) , .C2 ( n91 ) , .ZN ( n87 ) ) ;
XNOR2_X1 U191 (.A ( speed[6] ) , .B ( r116_carry[6] ) , .ZN ( N134 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI22_X1 U192 (.A1 ( n222 ) , .A2 ( N70 ) , .B1 ( n97 ) , .B2 ( n88 ) 
    , .ZN ( n144 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI222_X1 U193 (.VDD ( VDD ) , .VSS ( VSS ) , .A1 ( n9 ) , .A2 ( n89 ) 
    , .B1 ( speed[0] ) , .B2 ( n90 ) , .C1 ( N70 ) , .C2 ( n91 ) , .ZN ( n97 ) ) ;
OAI22_X1 U194 (.A1 ( n222 ) , .A2 ( n298 ) , .B1 ( n98 ) , .B2 ( n88 ) 
    , .ZN ( n145 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI222_X1 U195 (.VDD ( VDD ) , .VSS ( VSS ) , .A1 ( n2 ) , .A2 ( n89 ) 
    , .B1 ( N135 ) , .B2 ( n90 ) , .C1 ( N77 ) , .C2 ( n91 ) , .ZN ( n98 ) ) ;
XNOR2_X1 U196 (.A ( speed[7] ) , .B ( r116_carry[7] ) , .ZN ( N135 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AND2_X1 U197 (.A1 ( coast ) , .A2 ( n114 ) , .ZN ( n102 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
AOI211_X1 U198 (.A ( n84 ) , .B ( reset ) , .C1 ( n64 ) , .C2 ( n108 ) 
    , .ZN ( n66 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI211_X1 U199 (.A ( n38 ) , .B ( n85 ) , .C1 ( n233 ) , .C2 ( n730 ) 
    , .ZN ( n740 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X1 U200 (.A1 ( n86 ) , .A2 ( n83 ) , .ZN ( n85 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
OR4_X1 U201 (.A1 ( n770 ) , .A2 ( n99 ) , .A3 ( n100 ) , .A4 ( n101 ) 
    , .ZN ( n91 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI21_X1 U202 (.A ( throttle ) , .B1 ( n700 ) , .B2 ( n236 ) , .ZN ( n100 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AND2_X1 U203 (.A1 ( n102 ) , .A2 ( n81 ) , .ZN ( n99 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
INV_X1 U204 (.A ( resume ) , .ZN ( n233 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OR3_X1 U205 (.A1 ( n224 ) , .A2 ( reset ) , .A3 ( n116 ) , .ZN ( n47 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U206 (.A ( reset ) , .ZN ( n223 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND3_X1 U207 (.A1 ( n114 ) , .A2 ( n231 ) , .A3 ( throttle ) , .ZN ( n110 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI22_X1 U208 (.A1 ( n39 ) , .A2 ( n740 ) , .B1 ( n750 ) , .B2 ( n68 ) 
    , .ZN ( n136 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR3_X1 U209 (.A1 ( n760 ) , .A2 ( n228 ) , .A3 ( n770 ) , .ZN ( n750 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AND3_X1 U210 (.A1 ( set ) , .A2 ( N58 ) , .A3 ( throttle ) , .ZN ( n108 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI22_X1 U211 (.A1 ( n33 ) , .A2 ( n740 ) , .B1 ( n82 ) , .B2 ( n68 ) 
    , .ZN ( n137 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI21_X1 U212 (.A ( n84 ) , .B1 ( n83 ) , .B2 ( n233 ) , .ZN ( n82 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X1 U213 (.A1 ( n1 ) , .A2 ( reset ) , .ZN ( n125 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
OAI211_X1 U214 (.A ( n121 ) , .B ( n122 ) , .C1 ( n47 ) , .C2 ( n298 ) 
    , .ZN ( n1460 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI22_X1 U215 (.A1 ( N170 ) , .A2 ( n50 ) , .B1 ( N153 ) , .B2 ( n51 ) 
    , .ZN ( n122 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X1 U216 (.A1 ( cruisespeed[7] ) , .A2 ( n224 ) , .ZN ( n121 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI211_X1 U217 (.A ( n56 ) , .B ( n57 ) , .C1 ( n47 ) , .C2 ( n327 ) 
    , .ZN ( n1310 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI22_X1 U218 (.A1 ( N166 ) , .A2 ( n50 ) , .B1 ( N149 ) , .B2 ( n51 ) 
    , .ZN ( n57 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X1 U219 (.A1 ( cruisespeed[3] ) , .A2 ( n224 ) , .ZN ( n56 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI211_X1 U220 (.A ( n580 ) , .B ( n59 ) , .C1 ( n47 ) , .C2 ( n211 ) 
    , .ZN ( n1320 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI22_X1 U221 (.A1 ( N165 ) , .A2 ( n50 ) , .B1 ( N148 ) , .B2 ( n51 ) 
    , .ZN ( n59 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X1 U222 (.A1 ( cruisespeed[2] ) , .A2 ( n224 ) , .ZN ( n580 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI211_X1 U223 (.A ( n48 ) , .B ( n49 ) , .C1 ( n47 ) , .C2 ( n311 ) 
    , .ZN ( n1280 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI22_X1 U224 (.A1 ( N169 ) , .A2 ( n50 ) , .B1 ( N152 ) , .B2 ( n51 ) 
    , .ZN ( n49 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X1 U225 (.A1 ( cruisespeed[6] ) , .A2 ( n224 ) , .ZN ( n48 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI211_X1 U226 (.A ( n52 ) , .B ( n53 ) , .C1 ( n47 ) , .C2 ( n155 ) 
    , .ZN ( n129 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI22_X1 U227 (.A1 ( N168 ) , .A2 ( n50 ) , .B1 ( N151 ) , .B2 ( n51 ) 
    , .ZN ( n53 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X1 U228 (.A1 ( cruisespeed[5] ) , .A2 ( n224 ) , .ZN ( n52 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI211_X1 U229 (.A ( n60 ) , .B ( n61 ) , .C1 ( n47 ) , .C2 ( n210 ) 
    , .ZN ( n1330 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI22_X1 U230 (.A1 ( N164 ) , .A2 ( n50 ) , .B1 ( N147 ) , .B2 ( n51 ) 
    , .ZN ( n61 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X1 U231 (.A1 ( cruisespeed[1] ) , .A2 ( n224 ) , .ZN ( n60 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI211_X1 U232 (.A ( n123 ) , .B ( n124 ) , .C1 ( n47 ) , .C2 ( N70 ) 
    , .ZN ( n1470 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI22_X1 U233 (.A1 ( n218 ) , .A2 ( n50 ) , .B1 ( N146 ) , .B2 ( n51 ) 
    , .ZN ( n124 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X1 U234 (.A1 ( cruisespeed[0] ) , .A2 ( n224 ) , .ZN ( n123 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI211_X1 U235 (.A ( n54 ) , .B ( n55 ) , .C1 ( n47 ) , .C2 ( n213 ) 
    , .ZN ( n1300 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI22_X1 U236 (.A1 ( N167 ) , .A2 ( n50 ) , .B1 ( N150 ) , .B2 ( n51 ) 
    , .ZN ( n55 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X1 U237 (.A1 ( cruisespeed[4] ) , .A2 ( n224 ) , .ZN ( n54 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U238 (.A ( throttle ) , .ZN ( n229 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X1 U239 (.A1 ( n730 ) , .A2 ( n103 ) , .ZN ( n770 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
NAND3_X1 U240 (.A1 ( n81 ) , .A2 ( n234 ) , .A3 ( cancel ) , .ZN ( n103 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AND2_X1 U241 (.A1 ( accel ) , .A2 ( n127 ) , .ZN ( n109 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
OAI21_X1 U242 (.A ( n63 ) , .B1 ( n62 ) , .B2 ( n18 ) , .ZN ( n1340 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI211_X1 U243 (.A ( n62 ) , .B ( n223 ) , .C1 ( n64 ) , .C2 ( n65 ) 
    , .ZN ( n63 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI21_X1 U244 (.A ( n66 ) , .B1 ( n237 ) , .B2 ( n233 ) , .ZN ( n62 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U245 (.A ( n65 ) , .ZN ( n237 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U246 (.A ( brake ) , .ZN ( n234 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X1 U247 (.A1 ( n67 ) , .A2 ( n68 ) , .ZN ( n1350 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
AOI211_X1 U248 (.A ( n69 ) , .B ( n228 ) , .C1 ( resume ) , .C2 ( n65 ) 
    , .ZN ( n67 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI22_X1 U249 (.A1 ( throttle ) , .A2 ( n700 ) , .B1 ( n710 ) , .B2 ( n236 ) 
    , .ZN ( n69 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U250 (.A ( coast ) , .ZN ( n231 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U251 (.A ( n188 ) , .ZN ( N189 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
DFF_X1 cruisespeed_reg_7_ (.D ( n240 ) , .CK ( clk_G1B8I1 ) 
    , .Q ( cruisespeed[7] ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
DFF_X1 cruisespeed_reg_6_ (.D ( n245 ) , .CK ( clk_G1B8I1 ) 
    , .Q ( cruisespeed[6] ) , .QN ( n217 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
DFF_X1 cruisespeed_reg_5_ (.D ( n248 ) , .CK ( clk_G1B8I1 ) 
    , .Q ( cruisespeed[5] ) , .QN ( n208 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
DFF_X1 cruisespeed_reg_4_ (.D ( n252 ) , .CK ( clk_G1B8I3 ) 
    , .Q ( cruisespeed[4] ) , .QN ( n1670 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
DFF_X1 cruisespeed_reg_3_ (.D ( n259 ) , .CK ( clk_G1B8I3 ) 
    , .Q ( cruisespeed[3] ) , .QN ( n209 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
DFF_X1 cruisespeed_reg_2_ (.D ( n264 ) , .CK ( clk_G1B8I3 ) 
    , .Q ( cruisespeed[2] ) , .QN ( n1690 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
DFF_X1 cruisespeed_reg_1_ (.D ( n269 ) , .CK ( clk_G1B8I1 ) 
    , .Q ( cruisespeed[1] ) , .QN ( n1680 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
DFF_X1 cruisespeed_reg_0_ (.D ( n274 ) , .CK ( clk_G1B8I1 ) 
    , .Q ( cruisespeed[0] ) , .QN ( n218 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
DFF_X1 cruisectrl_reg (.D ( n164 ) , .CK ( clk_G1B8I2 ) , .Q ( cruisectrl ) 
    , .QN ( n18 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
DFF_X1 state_reg_2_ (.D ( n165 ) , .CK ( clk_G1B8I2 ) , .Q ( state[2] ) 
    , .QN ( n33 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
DFF_X1 state_reg_1_ (.D ( n338 ) , .CK ( clk_G1B8I2 ) , .Q ( state[1] ) 
    , .QN ( n38 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
DFF_X1 state_reg_0_ (.D ( n166 ) , .CK ( clk_G1B8I2 ) , .Q ( state[0] ) 
    , .QN ( n39 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
DFF_X1 speed_reg_7_ (.D ( n152 ) , .CK ( clk_G1B8I1 ) , .Q ( speed[7] ) 
    , .QN ( n216 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
DFF_X1 speed_reg_0_ (.D ( n167 ) , .CK ( clk_G1B8I3 ) , .Q ( speed[0] ) 
    , .QN ( N70 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
DFF_X1 speed_reg_6_ (.D ( n307 ) , .CK ( clk_G1B8I2 ) , .Q ( speed[6] ) 
    , .QN ( n215 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
DFF_X1 speed_reg_5_ (.D ( n168 ) , .CK ( clk_G1B8I2 ) , .Q ( speed[5] ) 
    , .QN ( n155 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
DFF_X1 speed_reg_4_ (.D ( n169 ) , .CK ( clk_G1B8I2 ) , .Q ( speed[4] ) 
    , .QN ( n213 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
DFF_X1 speed_reg_3_ (.D ( n170 ) , .CK ( clk_G1B8I3 ) , .Q ( speed[3] ) 
    , .QN ( n154 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
DFF_X1 speed_reg_2_ (.D ( n189 ) , .CK ( clk_G1B8I3 ) , .Q ( speed[2] ) 
    , .QN ( n211 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
DFF_X1 speed_reg_1_ (.D ( n335 ) , .CK ( clk_G1B8I3 ) , .Q ( speed[1] ) 
    , .QN ( n210 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR3_X1 U124 (.A1 ( n39 ) , .A2 ( state[2] ) , .A3 ( n38 ) , .ZN ( n81 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI22_X1 U125 (.A1 ( n1 ) , .A2 ( n234 ) , .B1 ( resume ) , .B2 ( n720 ) 
    , .ZN ( n90 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U126 (.A ( n111 ) , .ZN ( n222 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI211_X1 U127 (.A ( n86 ) , .B ( n227 ) , .C1 ( n233 ) , .C2 ( n83 ) 
    , .ZN ( n111 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U128 (.A ( n112 ) , .ZN ( n227 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI221_X1 U129 (.A ( n101 ) , .B1 ( n81 ) , .B2 ( n80 ) , .C1 ( N190 ) 
    , .C2 ( n113 ) , .ZN ( n112 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X1 U130 (.A1 ( n222 ) , .A2 ( n223 ) , .ZN ( n88 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
NOR2_X1 U131 (.A1 ( n109 ) , .A2 ( n102 ) , .ZN ( n115 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
NAND2_X1 U132 (.A1 ( n115 ) , .A2 ( n110 ) , .ZN ( n80 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
OAI21_X1 U133 (.A ( n225 ) , .B1 ( n104 ) , .B2 ( n1 ) , .ZN ( n89 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U134 (.A ( n760 ) , .ZN ( n225 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AOI211_X1 U135 (.A ( n109 ) , .B ( n230 ) , .C1 ( n79 ) , .C2 ( n188 ) 
    , .ZN ( n104 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U136 (.A ( n126 ) , .ZN ( n224 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI21_X1 U137 (.A ( n66 ) , .B1 ( n115 ) , .B2 ( n1 ) , .ZN ( n126 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AND2_X1 U138 (.A1 ( n109 ) , .A2 ( n125 ) , .ZN ( n51 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
AND2_X1 U139 (.A1 ( n102 ) , .A2 ( n125 ) , .ZN ( n50 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
NOR2_X1 U140 (.A1 ( n1 ) , .A2 ( n127 ) , .ZN ( n84 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
OAI211_X1 U141 (.A ( n106 ) , .B ( n226 ) , .C1 ( n105 ) , .C2 ( n236 ) 
    , .ZN ( n760 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U142 (.A ( n107 ) , .ZN ( n226 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NOR2_X1 U143 (.A1 ( n710 ) , .A2 ( n108 ) , .ZN ( n105 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
OAI22_X1 U144 (.A1 ( n720 ) , .A2 ( n233 ) , .B1 ( n700 ) , .B2 ( n229 ) 
    , .ZN ( n107 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND4_X1 U145 (.A1 ( n116 ) , .A2 ( n117 ) , .A3 ( n700 ) , .A4 ( n223 ) 
    , .ZN ( n86 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OR2_X1 U146 (.A1 ( n106 ) , .A2 ( n229 ) , .ZN ( n117 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
NOR2_X1 U147 (.A1 ( n64 ) , .A2 ( n84 ) , .ZN ( n116 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
NOR2_X1 U148 (.A1 ( n229 ) , .A2 ( n108 ) , .ZN ( n710 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
NAND2_X1 U149 (.A1 ( n740 ) , .A2 ( n223 ) , .ZN ( n68 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
AND3_X1 U150 (.A1 ( n231 ) , .A2 ( n229 ) , .A3 ( n114 ) , .ZN ( n79 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
AND3_X1 U151 (.A1 ( n79 ) , .A2 ( n81 ) , .A3 ( N189 ) , .ZN ( n101 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U152 (.A ( n78 ) , .ZN ( n228 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
OAI21_X1 U153 (.A ( n81 ) , .B1 ( n79 ) , .B2 ( n80 ) , .ZN ( n78 ) 
    , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U154 (.A ( n110 ) , .ZN ( n230 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U156 (.A ( n195 ) , .ZN ( n212 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
NAND2_X1 U157 (.A1 ( n720 ) , .A2 ( n1 ) , .ZN ( n113 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
INV_X1 U158 (.A ( n1520 ) , .ZN ( n160 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U72 (.A ( n295 ) , .ZN ( n296 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U73 (.A ( n216 ) , .ZN ( n297 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U74 (.A ( n297 ) , .ZN ( n298 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U75 (.A ( n145 ) , .ZN ( n299 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U76 (.A ( n299 ) , .ZN ( n300 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
CLKBUF_X1 U77 (.A ( n302 ) , .Z ( n301 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U78 (.A ( n305 ) , .ZN ( n302 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U79 (.A ( n301 ) , .ZN ( n303 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U80 (.A ( n144 ) , .ZN ( n304 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U81 (.A ( n304 ) , .ZN ( n305 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U82 (.A ( n309 ) , .ZN ( n306 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U83 (.A ( n306 ) , .ZN ( n307 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U84 (.A ( n138 ) , .ZN ( n308 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U85 (.A ( n308 ) , .ZN ( n309 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U86 (.A ( n215 ) , .ZN ( n310 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U87 (.A ( n310 ) , .ZN ( n311 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
CLKBUF_X1 U88 (.A ( n315 ) , .Z ( n312 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U89 (.A ( n312 ) , .ZN ( n313 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U90 (.A ( n313 ) , .ZN ( n314 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U91 (.A ( n139 ) , .ZN ( n315 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U92 (.A ( n314 ) , .ZN ( n316 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
CLKBUF_X1 U93 (.A ( n318 ) , .Z ( n317 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U94 (.A ( n321 ) , .ZN ( n318 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U95 (.A ( n317 ) , .ZN ( n319 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U96 (.A ( n140 ) , .ZN ( n320 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U97 (.A ( n320 ) , .ZN ( n321 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U98 (.A ( n141 ) , .ZN ( n322 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U99 (.A ( n322 ) , .ZN ( n323 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U100 (.A ( n323 ) , .ZN ( n324 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U101 (.A ( n324 ) , .ZN ( n325 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U102 (.A ( n154 ) , .ZN ( n326 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U103 (.A ( n326 ) , .ZN ( n327 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
CLKBUF_X1 U104 (.A ( n329 ) , .Z ( n328 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U105 (.A ( n332 ) , .ZN ( n329 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U106 (.A ( n328 ) , .ZN ( n330 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U107 (.A ( n142 ) , .ZN ( n331 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U108 (.A ( n331 ) , .ZN ( n332 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
CLKBUF_X1 U109 (.A ( n334 ) , .Z ( n333 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U110 (.A ( n337 ) , .ZN ( n334 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U111 (.A ( n333 ) , .ZN ( n335 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U112 (.A ( n143 ) , .ZN ( n336 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U113 (.A ( n336 ) , .ZN ( n337 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X4 INV_X1_G1B1I1 (.A ( clk_G1B7I1 ) , .ZN ( clk_G1B8I1 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
INV_X4 INV_X1_G1B1I3 (.A ( clk_G1B7I1 ) , .ZN ( clk_G1B8I3 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
INV_X4 INV_X1_G1B1I2 (.A ( clk_G1B7I1 ) , .ZN ( clk_G1B8I2 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
INV_X4 INV_X1_G1B2I1 (.A ( clk ) , .ZN ( clk_G1B7I1 ) , .VDD ( VDD ) 
    , .VSS ( VSS ) ) ;
INV_X1 U1 (.A ( n81 ) , .ZN ( n1 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
BUF_X1 U2 (.A ( n296 ) , .Z ( n152 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U3 (.A ( n277 ) , .ZN ( n153 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X8 U4 (.A ( n153 ) , .ZN ( n164 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
BUF_X1 U5 (.A ( n282 ) , .Z ( n165 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
BUF_X1 U6 (.A ( n292 ) , .Z ( n166 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
BUF_X1 U7 (.A ( n303 ) , .Z ( n167 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
BUF_X1 U8 (.A ( n316 ) , .Z ( n168 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
BUF_X1 U9 (.A ( n319 ) , .Z ( n169 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
BUF_X1 U10 (.A ( n325 ) , .Z ( n170 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
BUF_X1 U11 (.A ( n330 ) , .Z ( n189 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
CLKBUF_X1 U12 (.A ( n238 ) , .Z ( n190 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U13 (.A ( n239 ) , .ZN ( n235 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U14 (.A ( n235 ) , .ZN ( n238 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U15 (.A ( n1460 ) , .ZN ( n239 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U16 (.A ( n190 ) , .ZN ( n240 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
CLKBUF_X1 U17 (.A ( n244 ) , .Z ( n241 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U18 (.A ( n1280 ) , .ZN ( n242 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U19 (.A ( n242 ) , .ZN ( n243 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U20 (.A ( n243 ) , .ZN ( n244 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U21 (.A ( n241 ) , .ZN ( n245 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
CLKBUF_X1 U22 (.A ( n247 ) , .Z ( n246 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U23 (.A ( n249 ) , .ZN ( n247 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U24 (.A ( n246 ) , .ZN ( n248 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
BUF_X32 U25 (.A ( n129 ) , .Z ( n249 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
CLKBUF_X1 U26 (.A ( n251 ) , .Z ( n250 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U27 (.A ( n254 ) , .ZN ( n251 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U28 (.A ( n250 ) , .ZN ( n252 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U29 (.A ( n1300 ) , .ZN ( n253 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U30 (.A ( n253 ) , .ZN ( n254 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
CLKBUF_X1 U31 (.A ( n258 ) , .Z ( n255 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U32 (.A ( n1310 ) , .ZN ( n256 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U33 (.A ( n256 ) , .ZN ( n257 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U34 (.A ( n257 ) , .ZN ( n258 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U35 (.A ( n255 ) , .ZN ( n259 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
CLKBUF_X1 U36 (.A ( n263 ) , .Z ( n260 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U37 (.A ( n1320 ) , .ZN ( n261 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U38 (.A ( n261 ) , .ZN ( n262 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U39 (.A ( n262 ) , .ZN ( n263 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U40 (.A ( n260 ) , .ZN ( n264 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
CLKBUF_X1 U41 (.A ( n268 ) , .Z ( n265 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U42 (.A ( n1330 ) , .ZN ( n266 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U43 (.A ( n266 ) , .ZN ( n267 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U44 (.A ( n267 ) , .ZN ( n268 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U45 (.A ( n265 ) , .ZN ( n269 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
CLKBUF_X1 U46 (.A ( n273 ) , .Z ( n270 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U47 (.A ( n1470 ) , .ZN ( n271 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U48 (.A ( n271 ) , .ZN ( n272 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U49 (.A ( n272 ) , .ZN ( n273 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U50 (.A ( n270 ) , .ZN ( n274 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
CLKBUF_X1 U51 (.A ( n276 ) , .Z ( n275 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U52 (.A ( n279 ) , .ZN ( n276 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U53 (.A ( n275 ) , .ZN ( n277 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U54 (.A ( n1340 ) , .ZN ( n278 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U55 (.A ( n278 ) , .ZN ( n279 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
CLKBUF_X1 U56 (.A ( n281 ) , .Z ( n280 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U57 (.A ( n284 ) , .ZN ( n281 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U58 (.A ( n280 ) , .ZN ( n282 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U59 (.A ( n137 ) , .ZN ( n283 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U60 (.A ( n283 ) , .ZN ( n284 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
BUF_X1 U61 (.A ( n289 ) , .Z ( n285 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U62 (.A ( n288 ) , .ZN ( n286 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U63 (.A ( n286 ) , .ZN ( n287 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U64 (.A ( n1350 ) , .ZN ( n288 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U65 (.A ( n287 ) , .ZN ( n289 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
CLKBUF_X1 U66 (.A ( n291 ) , .Z ( n290 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U67 (.A ( n294 ) , .ZN ( n291 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U68 (.A ( n290 ) , .ZN ( n292 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U69 (.A ( n136 ) , .ZN ( n293 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X32 U70 (.A ( n293 ) , .ZN ( n294 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
INV_X1 U71 (.A ( n300 ) , .ZN ( n295 ) , .VDD ( VDD ) , .VSS ( VSS ) ) ;
endmodule


