set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction horizontal  -start_at 2.3000 -nets VDD -layer 23 -width 3.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 101.5000 -nets VDD -layer 23 -width 3.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 101.6900 -nets VDD -layer 25 -width 3.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 2.3000 -nets VDD -layer 25 -width 3.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 2.3000 -nets VDD -layer 27 -width 3.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 101.5000 -nets VDD -layer 27 -width 3.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 101.6900 -nets VDD -layer 29 -width 3.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 2.3000 -nets VDD -layer 29 -width 3.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 6.1000 -nets VSS -layer 23 -width 3.0000 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 97.7000 -nets VSS -layer 23 -width 3.0000 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 97.8900 -nets VSS -layer 25 -width 3.0000 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 6.1000 -nets VSS -layer 25 -width 3.0000 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 6.1000 -nets VSS -layer 27 -width 3.0000 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 97.7000 -nets VSS -layer 27 -width 3.0000 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 97.8900 -nets VSS -layer 29 -width 3.0000 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 6.1000 -nets VSS -layer 29 -width 3.0000 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal6 straps for net VDD
create_power_straps  -direction vertical  -start_at 12.1750 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 16.7350 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 20.5350 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 25.0950 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 28.8950 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 32.6950 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 37.2550 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 41.0550 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 45.6150 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 49.4150 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 53.9750 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 57.7750 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 62.3350 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 66.1350 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 70.6950 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 74.4950 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 79.0550 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 82.8550 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 87.4150 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 91.2150 -nets VDD  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal6 straps for net VSS
create_power_straps  -direction vertical  -start_at 12.5850 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 17.1450 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 20.9450 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 25.5050 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 29.3050 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 33.1050 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 37.6650 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 41.4650 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 46.0250 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 49.8250 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 54.3850 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 58.1850 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 62.7450 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 66.5450 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 71.1050 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 74.9050 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 79.4650 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 83.2650 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 87.8250 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 91.6250 -nets VSS  -layer 21 -width 0.1400 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal7 straps for net VDD
create_power_straps  -direction horizontal  -start_at 11.5350 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 16.0950 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 20.6550 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 23.6950 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 28.2550 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 32.8150 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 37.3750 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 40.4150 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 44.9750 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 49.5350 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 54.0950 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 57.1350 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 61.6950 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 66.2550 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 70.8150 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 73.8550 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 78.4150 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 82.9750 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 86.0150 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 90.5750 -nets VDD  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal7 straps for net VSS
create_power_straps  -direction horizontal  -start_at 12.4650 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 17.0250 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 21.5850 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 24.6250 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 29.1850 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 33.7450 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 38.3050 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 41.3450 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 45.9050 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 50.4650 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 55.0250 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 58.0650 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 62.6250 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 67.1850 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 71.7450 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 74.7850 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 79.3450 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 83.9050 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 86.9450 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 91.5050 -nets VSS  -layer 23 -width 0.4000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VDD
create_power_straps  -direction vertical  -start_at 12.3600 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 16.9200 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 19.9600 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 24.5200 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 29.0800 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 32.1200 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 36.6800 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 41.2400 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 45.8000 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 48.8400 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 53.4000 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 57.9600 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 62.5200 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 65.5600 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 70.1200 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 74.6800 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 79.2400 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 82.2800 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 86.8400 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 91.4000 -nets VDD  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VSS
create_power_straps  -direction vertical  -start_at 13.1600 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 17.7200 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 20.7600 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 25.3200 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 29.8800 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 32.9200 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 37.4800 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 42.0400 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 46.6000 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 49.6400 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 54.2000 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 58.7600 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 63.3200 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 66.3600 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 70.9200 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 75.4800 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 80.0400 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 83.0800 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 87.6400 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 92.2000 -nets VSS  -layer 25 -width 0.4000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VDD
create_power_straps  -direction horizontal  -start_at 11.2000 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 17.2800 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 20.3200 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 23.3600 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 29.4400 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 32.4800 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 35.5200 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 41.6000 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 44.6400 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 47.6800 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 53.7600 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 56.8000 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 62.8800 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 65.9200 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 68.9600 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 75.0400 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 78.0800 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 81.1200 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 87.2000 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 90.2400 -nets VDD  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.1900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VSS
create_power_straps  -direction horizontal  -start_at 12.8000 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 18.8800 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 21.9200 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 24.9600 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 31.0400 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 34.0800 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 37.1200 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 43.2000 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 46.2400 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 49.2800 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 55.3600 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 58.4000 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 64.4800 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 67.5200 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 70.5600 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 76.6400 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 79.6800 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 82.7200 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 88.8000 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 91.8400 -nets VSS  -layer 27 -width 0.8000 -pitch_within_group 4.1520 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.3900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal10 straps for net VDD
create_power_straps  -direction vertical  -start_at 12.7200 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 15.7600 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 18.8000 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 24.8800 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 27.9200 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 30.9600 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 37.0400 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 40.0800 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 46.1600 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 49.2000 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 52.2400 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 58.3200 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 61.3600 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 64.4000 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 70.4800 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 73.5200 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 79.6000 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 82.6400 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 85.6800 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 91.7600 -nets VDD  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 103.0000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal10 straps for net VSS
create_power_straps  -direction vertical  -start_at 14.3200 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 17.3600 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 20.4000 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 26.4800 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 29.5200 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 32.5600 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 38.6400 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 41.6800 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 47.7600 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 50.8000 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 53.8400 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 59.9200 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 62.9600 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 66.0000 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 72.0800 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 75.1200 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 81.2000 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 84.2400 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 87.2800 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 93.3600 -nets VSS  -layer 29 -width 0.8000 -pitch_within_group 4.1610 -start_low_ends coordinate  -start_low_ends_coordinate 4.6000 -start_high_ends coordinate  -start_high_ends_coordinate 99.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
